sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
branches:  # remove travis double-check on pull requests in main repo
  only:
    - master
    - /^\d\.\d+$/
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=flake8
  - TOXENV=perf
before_install:
  - pip install codecov
install:
  - pip install 'coverage<4'
  - pip install tox coveralls
script:
  - tox
after_success:
  - coveralls
  - codecov
